import Link from 'next/link';import { notFound } from 'next/navigation';
import { ConfirmUploadButton } from '@/features/uploads/components/confirm-upload-button';
import { findUpload } from '@/features/uploads/repositories/upload.repository';
import { uploadIdSchema } from '@/features/uploads/schemas/upload.schema';
import { requireRole } from '@/shared/auth/authorization';
import { getUploadTableDisplayName } from '@/features/uploads/config/supported-upload-tables';
import { UploadAutoRefresh } from '@/features/uploads/components/upload-auto-refresh';

export default async function UploadDetailPage({params}:{params:Promise<{uploadId:string}>}){const user=await requireRole(['super_admin','client_admin','client_user']);const parsed=uploadIdSchema.safeParse((await params).uploadId);if(!parsed.success)notFound();const upload=await findUpload(user,parsed.data);if(!upload)notFound();return <><UploadAutoRefresh status={upload.status}/><main className="px-6 py-8 lg:px-8"><div className="mx-auto max-w-5xl"><Link href="/portal/uploads" className="text-sm font-medium text-slate-600">← Volver al historial</Link><h1 className="mt-5 text-3xl font-semibold">Resultado de validación</h1><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Campaña',upload.campaignName],['Tabla',getUploadTableDisplayName(upload.targetTable)],['Filas',String(upload.totalRows)],['Estado',upload.status]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-medium">{value}</p></div>)}</div><section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">Configuración</h2><p className="mt-2 text-sm text-slate-600">Clave: {upload.upsertKeyColumns.join(' + ')}</p><p className="mt-1 text-sm text-slate-600">Columnas: {upload.headers.join(', ')}</p><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><p>Válidas: <strong>{upload.validRows}</strong></p><p>Inválidas: <strong>{upload.invalidRows}</strong></p><p>Errores: <strong>{upload.errors.length}</strong></p></div></section>{upload.errors.length>0&&<section className="mt-6 rounded-xl border border-red-200 bg-red-50 p-6"><h2 className="font-semibold text-red-900">Errores encontrados</h2><div className="mt-3 max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Fila</th><th>Columna</th><th>Detalle</th></tr></thead><tbody>{upload.errors.map((error,index)=><tr key={index} className="border-t border-red-200"><td className="py-2">{error.rowNumber??'Archivo'}</td><td>{error.columnName??'—'}</td><td>{error.message}</td></tr>)}</tbody></table></div></section>}{upload.status==='ready_for_confirmation'&&<div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-6"><p className="mb-4 text-sm text-emerald-900">El archivo es válido. Confirma para ejecutar el upsert dentro de una transacción.</p><ConfirmUploadButton uploadId={upload.id}/></div>}{upload.status==='completed'&&<div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-6">Insertadas: <strong>{upload.insertedRows}</strong> · Actualizadas: <strong>{upload.updatedRows}</strong></div>}</div></main></>}
