import type {PoolConnection,ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import type {AuthenticatedPortalUser} from '@/features/users/repositories/user.repository';
import type {CampaignUploadOption,UploadError,UploadSummary,UploadStatus} from '@/features/uploads/types/upload';
import {getUploadFileType} from '@/features/uploads/config/supported-upload-tables';
import {db} from '@/shared/database/mysql';
interface CampaignRow extends RowDataPacket{id:number;name:string;code:string;client_name:string}
export interface ConfigRow extends RowDataPacket{id:number;target_table:string;upsert_key_columns:string|string[]}
export interface UploadRow extends RowDataPacket{id:number;campaign_id:number;campaign_name:string;campaign_code:string;uploaded_by:number;original_filename:string;file_size_bytes:number;s3_object_key:string|null;s3_multipart_upload_id:string|null;status:UploadStatus;target_table:string;upsert_key_columns:string|string[];headers:string|string[]|null;schema_hash:string|null;staging_table:string|null;total_rows:number;valid_rows:number;invalid_rows:number;inserted_rows:number;updated_rows:number;error_rows:number;progress_rows:number;progress_percent:number;error_message:string|null;created_at:Date;completed_at:Date|null}
interface ErrorRow extends RowDataPacket{row_number:number|null;column_name:string|null;error_code:string;message:string}
const array=(v:string|string[]|null):string[]=>v===null?[]:typeof v==='string'?JSON.parse(v) as string[]:v;
const SELECT=`SELECT u.*,c.name campaign_name,c.code campaign_code,f.target_table,f.upsert_key_columns FROM portal_file_uploads u JOIN portal_campaigns c ON c.id=u.campaign_id JOIN portal_campaign_file_configs f ON f.id=u.config_id`;
export async function findAccessibleCampaigns(user:AuthenticatedPortalUser):Promise<CampaignUploadOption[]>{const p:number[]=[];let a='';if(user.role!=='super_admin'){a='AND c.id IN(SELECT campaign_id FROM portal_user_campaigns WHERE user_id=?)';p.push(user.id)}const[r]=await db.execute<CampaignRow[]>(`SELECT c.id,c.name,c.code,cl.name client_name FROM portal_campaigns c JOIN portal_clients cl ON cl.id=c.client_id WHERE c.status='active' AND cl.status='active' ${a} ORDER BY cl.name,c.name`,p);return r.map(x=>({id:Number(x.id),name:x.name,code:x.code,clientName:x.client_name}))}
export async function findAccessibleCampaign(u:AuthenticatedPortalUser,id:number){return(await findAccessibleCampaigns(u)).find(c=>c.id===id)??null}
export async function findConfigs(id:number):Promise<Array<ConfigRow&{upsert_key_columns:string[]}>>{const[r]=await db.execute<ConfigRow[]>('SELECT id,target_table,upsert_key_columns FROM portal_campaign_file_configs WHERE campaign_id=? AND status=\'active\'',[id]);return r.map(x=>({...x,upsert_key_columns:array(x.upsert_key_columns)}))}
export async function findConfig(id:number,table?:string){const c=await findConfigs(id);return table?c.find(x=>x.target_table===table)??null:c[0]??null}
export async function upsertConfig(c:PoolConnection,id:number,table:string,keys:string[]){const type=getUploadFileType(table);if(!type)throw new Error('Tabla no permitida');await c.execute(`INSERT INTO portal_campaign_file_configs(campaign_id,file_type,target_table,upsert_key_columns,status) VALUES (?,?,?,?, 'active') ON DUPLICATE KEY UPDATE target_table=VALUES(target_table),upsert_key_columns=VALUES(upsert_key_columns),status='active'`,[id,type,table,JSON.stringify(keys)]);const[r]=await c.execute<ConfigRow[]>('SELECT id,target_table,upsert_key_columns FROM portal_campaign_file_configs WHERE campaign_id=? AND file_type=? LIMIT 1',[id,type]);return Number(r[0]!.id)}
export async function createPendingUpload(c:PoolConnection,i:{campaignId:number;configId:number;userId:number;filename:string;size:number}){const[r]=await c.execute<ResultSetHeader>(`INSERT INTO portal_file_uploads(campaign_id,config_id,uploaded_by,original_filename,file_size_bytes,status,expires_at) VALUES(?,?,?,?,?,'uploading',DATE_ADD(NOW(),INTERVAL 24 HOUR))`,[i.campaignId,i.configId,i.userId,i.filename,i.size]);return r.insertId}
export async function saveMultipart(id:number,key:string,multipart:string){await db.execute('UPDATE portal_file_uploads SET s3_object_key=?,s3_multipart_upload_id=? WHERE id=?',[key,multipart,id])}
export async function lockOwnedUpload(c:PoolConnection,id:number,userId:number){const[r]=await c.execute<UploadRow[]>(`${SELECT} WHERE u.id=? AND u.uploaded_by=? LIMIT 1 FOR UPDATE`,[id,userId]);return r[0]??null}
export async function getWorkerUpload(id:number){const[r]=await db.execute<UploadRow[]>(`${SELECT} WHERE u.id=? LIMIT 1`,[id]);return r[0]??null}
export async function findUpload(u:AuthenticatedPortalUser,id:number):Promise<UploadSummary|null>{const[r]=await db.execute<UploadRow[]>(`${SELECT} WHERE u.id=? AND u.uploaded_by=? LIMIT 1`,[id,u.id]);const x=r[0];if(!x)return null;const[e]=await db.execute<ErrorRow[]>('SELECT `row_number`,column_name,error_code,message FROM portal_file_upload_errors WHERE upload_id=? ORDER BY COALESCE(`row_number`,0),id LIMIT 500',[id]);return{id:Number(x.id),campaignId:Number(x.campaign_id),campaignName:x.campaign_name,filename:x.original_filename,status:x.status,targetTable:x.target_table,upsertKeyColumns:array(x.upsert_key_columns),headers:array(x.headers),totalRows:Number(x.total_rows),validRows:Number(x.valid_rows),invalidRows:Number(x.invalid_rows),insertedRows:Number(x.inserted_rows),updatedRows:Number(x.updated_rows),errorRows:Number(x.error_rows),progressRows:Number(x.progress_rows),progressPercent:Number(x.progress_percent),errorMessage:x.error_message,createdAt:x.created_at,completedAt:x.completed_at,errors:e.map(y=>({rowNumber:y.row_number===null?null:Number(y.row_number),columnName:y.column_name,code:y.error_code,message:y.message}))}}
export async function findUploads(u:AuthenticatedPortalUser,page:number,size:number){const[count]=await db.execute<Array<RowDataPacket&{total:number}>>('SELECT COUNT(*) total FROM portal_file_uploads WHERE uploaded_by=?',[u.id]);const[r]=await db.query<UploadRow[]>(`${SELECT} WHERE u.uploaded_by=? ORDER BY u.created_at DESC LIMIT ? OFFSET ?`,[u.id,size,(page-1)*size]);const items=await Promise.all(r.map(x=>findUpload(u,Number(x.id))));return{items:items.filter((x):x is UploadSummary=>x!==null),total:Number(count[0]?.total??0)}}
export async function updateUpload(id:number,set:string,values:Array<string|number|null>=[]){await db.execute(`UPDATE portal_file_uploads SET ${set} WHERE id=?`,[...values,id])}
export async function insertErrors(id:number,errors:UploadError[]){if(errors.length)await db.query(`INSERT INTO portal_file_upload_errors(upload_id,\`row_number\`,column_name,error_code,message) VALUES ${errors.map(()=>'(?,?,?,?,?)').join(',')}`,errors.flatMap(e=>[id,e.rowNumber,e.columnName,e.code,e.message]))}
