import {randomUUID} from 'node:crypto';
import {AbortMultipartUploadCommand,CompleteMultipartUploadCommand,CreateMultipartUploadCommand,DeleteObjectCommand,HeadObjectCommand,S3Client,UploadPartCommand} from '@aws-sdk/client-s3';
import {BatchClient,SubmitJobCommand} from '@aws-sdk/client-batch';
import {getSignedUrl} from '@aws-sdk/s3-request-presigner';
import type {AuthenticatedPortalUser} from '@/features/users/repositories/user.repository';
import {UploadServiceError} from '@/features/uploads/errors/upload-service-error';
import {createPendingUpload,findAccessibleCampaign,findConfig,lockOwnedUpload,saveMultipart,updateUpload,upsertConfig} from '@/features/uploads/repositories/upload.repository';
import {inspectTable} from '@/features/uploads/services/schema-inspection';
import {db} from '@/shared/database/mysql';
const MAX=120*1024*1024,PART=10*1024*1024;
const bucket=()=>{if(!process.env.UPLOADS_S3_BUCKET)throw new Error('Falta UPLOADS_S3_BUCKET');return process.env.UPLOADS_S3_BUCKET};
const s3=new S3Client({region:process.env.REGION}),batch=new BatchClient({region:process.env.REGION});
async function job(id:number,mode:'validate'|'process'){const q=process.env.UPLOADS_BATCH_JOB_QUEUE,d=process.env.UPLOADS_BATCH_JOB_DEFINITION;if(!q||!d)throw new Error('Falta configuración de AWS Batch');const r=await batch.send(new SubmitJobCommand({jobName:`csv-${mode}-${id}`,jobQueue:q,jobDefinition:d,containerOverrides:{environment:[{name:'UPLOAD_ID',value:String(id)},{name:'WORKER_MODE',value:mode}]}}));if(!r.jobId)throw new Error('AWS Batch no devolvió jobId');return r.jobId}
export async function initiateLargeUpload(user:AuthenticatedPortalUser,input:{campaignId:number;targetTable:string;upsertKeyColumns:string[];filename:string;fileSize:number;contentType?:string}){if(input.fileSize>MAX)throw new UploadServiceError('FILE_TOO_LARGE','El archivo supera 120 MB.',413);const campaign=await findAccessibleCampaign(user,input.campaignId);if(!campaign)throw new UploadServiceError('CAMPAIGN_NOT_AVAILABLE','La campaña no está disponible.',403);const schema=await inspectTable(campaign.code,input.targetTable);if(!schema.uniqueIndexes.some(i=>JSON.stringify(i.columns)===JSON.stringify(input.upsertKeyColumns)))throw new UploadServiceError('INVALID_UPSERT_KEY','La clave debe coincidir con un índice único.',400);const config=await findConfig(input.campaignId,input.targetTable);if(user.role==='client_user'&&(!config||JSON.stringify(config.upsert_key_columns)!==JSON.stringify(input.upsertKeyColumns)))throw new UploadServiceError('CONFIGURATION_FORBIDDEN','Un administrador debe aprobar esta configuración.',403);const c=await db.getConnection();let id=0;try{await c.beginTransaction();const configId=await upsertConfig(c,input.campaignId,input.targetTable,input.upsertKeyColumns);id=await createPendingUpload(c,{campaignId:input.campaignId,configId,userId:user.id,filename:input.filename.slice(0,255),size:input.fileSize});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}const key=`temporary/${user.id}/${id}/${randomUUID()}.csv`;try{const r=await s3.send(new CreateMultipartUploadCommand({Bucket:bucket(),Key:key,ContentType:input.contentType||'text/csv',ServerSideEncryption:process.env.UPLOADS_KMS_KEY_ID?'aws:kms':'AES256',SSEKMSKeyId:process.env.UPLOADS_KMS_KEY_ID,Metadata:{uploadId:String(id)}}));if(!r.UploadId)throw new Error('S3 no devolvió UploadId');await saveMultipart(id,key,r.UploadId);const parts=await Promise.all(Array.from({length:Math.ceil(input.fileSize/PART)},async(_,n)=>({partNumber:n+1,url:await getSignedUrl(s3,new UploadPartCommand({Bucket:bucket(),Key:key,UploadId:r.UploadId,PartNumber:n+1}),{expiresIn:3600})})));return{uploadId:id,partSize:PART,parts}}catch(e){await updateUpload(id,"status='failed',error_message=?",[e instanceof Error?e.message.slice(0,1000):'No se inició la carga']);throw e}}
export async function completeLargeUpload(user:AuthenticatedPortalUser,id:number,parts:{partNumber:number;eTag:string}[]){const c=await db.getConnection();let objectKey:string|null=null;try{await c.beginTransaction();const r=await lockOwnedUpload(c,id,user.id);if(!r)throw new UploadServiceError('UPLOAD_NOT_FOUND','La carga no existe.',404);if(r.status!=='uploading'||!r.s3_object_key||!r.s3_multipart_upload_id)throw new UploadServiceError('INVALID_UPLOAD_STATUS','La carga no está abierta.',409);objectKey=r.s3_object_key;await s3.send(new CompleteMultipartUploadCommand({Bucket:bucket(),Key:r.s3_object_key,UploadId:r.s3_multipart_upload_id,MultipartUpload:{Parts:parts.map(p=>({PartNumber:p.partNumber,ETag:p.eTag}))}}));const h=await s3.send(new HeadObjectCommand({Bucket:bucket(),Key:r.s3_object_key}));if(Number(h.ContentLength)!==Number(r.file_size_bytes))throw new Error('El tamaño recibido no coincide.');const jobId=await job(id,'validate');await c.execute("UPDATE portal_file_uploads SET status='queued_validation',batch_validation_job_id=? WHERE id=?",[jobId,id]);await c.commit();return{uploadId:id,status:'queued_validation'}}catch(e){await c.rollback();if(objectKey){try{await s3.send(new DeleteObjectCommand({Bucket:bucket(),Key:objectKey}))}catch(cleanup){console.error('No fue posible eliminar el objeto tras fallar Batch:',cleanup)}await updateUpload(id,"status='failed',s3_object_key=NULL,s3_multipart_upload_id=NULL,error_message=?",[e instanceof Error?e.message.slice(0,1000):'No se programó la validación'])}throw e}finally{c.release()}}
export async function abortLargeUpload(user:AuthenticatedPortalUser,id:number){const c=await db.getConnection();try{await c.beginTransaction();const r=await lockOwnedUpload(c,id,user.id);if(!r)throw new UploadServiceError('UPLOAD_NOT_FOUND','La carga no existe.',404);if(r.s3_object_key&&r.s3_multipart_upload_id)await s3.send(new AbortMultipartUploadCommand({Bucket:bucket(),Key:r.s3_object_key,UploadId:r.s3_multipart_upload_id}));else if(r.s3_object_key)await s3.send(new DeleteObjectCommand({Bucket:bucket(),Key:r.s3_object_key}));await c.execute("UPDATE portal_file_uploads SET status='cancelled',s3_object_key=NULL,s3_multipart_upload_id=NULL WHERE id=?",[id]);await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function queueProcessing(user:AuthenticatedPortalUser,id:number){const c=await db.getConnection();try{await c.beginTransaction();const r=await lockOwnedUpload(c,id,user.id);if(!r)throw new UploadServiceError('UPLOAD_NOT_FOUND','La carga no existe.',404);if(r.status!=='ready_for_confirmation')throw new UploadServiceError('INVALID_UPLOAD_STATUS','La carga no está lista.',409);const jobId=await job(id,'process');await c.execute("UPDATE portal_file_uploads SET status='queued_processing',confirmed_by=?,confirmed_at=NOW(),batch_processing_job_id=? WHERE id=?",[user.id,jobId,id]);await c.commit();return{uploadId:id,status:'queued_processing'}}catch(e){await c.rollback();throw e}finally{c.release()}}
